In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [37]:
df = data[['Glucose','Insulin','DiabetesPedigreeFunction','Age','Outcome']]

In [38]:
df

Glucose  Insulin  DiabetesPedigreeFunction  Age  Outcome
0        148        0                     0.627   50        1
1         85        0                     0.351   31        0
2        183        0                     0.672   32        1
3         89       94                     0.167   21        0
4        137      168                     2.288   33        1
..       ...      ...                       ...  ...      ...
763      101      180                     0.171   63        0
764      122        0                     0.340   27        0
765      121      112                     0.245   30        0
766      126        0                     0.349   47        1
767       93        0                     0.315   23        0

[768 rows x 5 columns]

In [39]:
X = df.iloc[:,:4].values
y = df.iloc[:,-1].values

In [40]:
X

array([[148.   ,   0.   ,   0.627,  50.   ],
       [ 85.   ,   0.   ,   0.351,  31.   ],
       [183.   ,   0.   ,   0.672,  32.   ],
       ...,
       [121.   , 112.   ,   0.245,  30.   ],
       [126.   ,   0.   ,   0.349,  47.   ],
       [ 93.   ,   0.   ,   0.315,  23.   ]])

In [41]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [43]:
X = scaler.fit_transform(X)
X

array([[ 0.84832379, -0.69289057,  0.46849198,  1.4259954 ],
       [-1.12339636, -0.69289057, -0.36506078, -0.19067191],
       [ 1.94372388, -0.69289057,  0.60439732, -0.10558415],
       ...,
       [ 0.00330087,  0.27959377, -0.68519336, -0.27575966],
       [ 0.1597866 , -0.69289057, -0.37110101,  1.17073215],
       [-0.8730192 , -0.69289057, -0.47378505, -0.87137393]])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=1)

In [45]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

In [46]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [47]:
y_pred = clf.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6948051948051948

In [49]:
param_dist = {
    'criterion':['gini','entropy'],
    'max_depth':[1,2,3,4,5,6,7,None]
}

In [50]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(clf, param_grid=param_dist, cv=10, n_jobs=-1)

In [52]:
grid.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, None]})

In [53]:
grid.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [54]:
grid.best_score_

0.7293759915388683

In [55]:
grid.best_params_

{'criterion': 'entropy', 'max_depth': 3}