In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_boston
boston=load_boston()

In [3]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)

In [5]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [6]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [7]:
df_x=pd.DataFrame(boston.data,columns=boston.feature_names)
df_y=pd.DataFrame(boston.target,columns=['medv'])

In [8]:
df_x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [9]:
reg=linear_model.LinearRegression()

In [10]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=3)

In [11]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
reg.coef_

array([[-1.23897571e-01,  4.81822924e-02, -4.74497796e-02,
         3.36938950e+00, -1.56635488e+01,  3.59419367e+00,
        -9.33206067e-03, -1.47089101e+00,  3.05053544e-01,
        -1.08397039e-02, -9.08791339e-01,  1.00352939e-02,
        -4.77714677e-01]])

In [13]:
y_predict=reg.predict(x_test)

In [14]:
x_test.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
224  0.31533   0.0   6.20   0.0  0.504  8.266  78.3  2.8944   8.0  307.0   
137  0.35233   0.0  21.89   0.0  0.624  6.454  98.4  1.8498   4.0  437.0   
453  8.24809   0.0  18.10   0.0  0.713  7.393  99.3  2.4527  24.0  666.0   
303  0.10000  34.0   6.09   0.0  0.433  6.982  17.7  5.4917   7.0  329.0   
254  0.04819  80.0   3.64   0.0  0.392  6.108  32.0  9.2203   1.0  315.0   

     PTRATIO       B  LSTAT  
224     17.4  385.05   4.14  
137     21.2  394.08  14.59  
453     20.2  375.87  16.74  
303     16.1  390.43   4.86  
254     16.4  392.89   6.57

In [15]:
y_predict

array([[37.54157616],
       [18.76483601],
       [22.36983893],
       [32.80195443],
       [24.28067045],
       [23.45046273],
       [18.97004495],
       [ 7.25837229],
       [20.90563109],
       [17.85625667],
       [13.9909041 ],
       [31.84086213],
       [36.06002933],
       [31.32636351],
       [ 7.69171028],
       [11.84051203],
       [23.47421328],
       [14.89222846],
       [12.83531594],
       [29.68317709],
       [26.89848085],
       [35.17415212],
       [27.19221597],
       [24.11468978],
       [13.72103765],
       [24.90234939],
       [20.91816609],
       [19.04157959],
       [19.24815482],
       [24.59866318],
       [14.91248208],
       [34.33862834],
       [21.63486788],
       [19.51442392],
       [19.44037044],
       [17.93274664],
       [21.43643542],
       [32.19385315],
       [15.33264981],
       [21.78729365],
       [17.11914571],
       [10.65530927],
       [25.25887578],
       [17.36938898],
       [23.61750096],
       [25

In [16]:
y_predict[0]

array([37.54157616])

In [17]:
# mean squared error
print('mean square error: %.2f' %mean_squared_error(y_test,y_predict))

mean square error: 16.94


In [18]:
# R2 score
print('R2: %.2f' % r2_score(y_test,y_predict))

R2: 0.80
