In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1)) #converts rows in column
y=np.array([5,20,14,32,22,38])

In [3]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [4]:
 x1=np.array([5,15,25,35,45,55])

In [5]:
type(x1)

numpy.ndarray

In [6]:
x1.shape

(6,)

In [7]:
y

array([ 5, 20, 14, 32, 22, 38])

In [8]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])

In [9]:
a=np.arange(1,28)

In [10]:
a.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
b=np.arange(1,11)

In [12]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b=b.reshape(-1,2)

In [14]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
b.shape

(5, 2)

In [16]:
model=LinearRegression()

In [17]:
from sklearn.metrics import mean_squared_error, r2_score

In [18]:
(x,y)

(array([[ 5],
        [15],
        [25],
        [35],
        [45],
        [55]]), array([ 5, 20, 14, 32, 22, 38]))

In [19]:
model.fit(x,y) # finds the points that best fit the points ,finds the value of m and c in y=mx+c

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
r_sq=model.score(x,y) # gives the value of r2_score

In [21]:
print('coefficient of determination',r_sq)

coefficient of determination 0.715875613747954


In [22]:
type(model)

sklearn.linear_model.base.LinearRegression

In [23]:
dir(model)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_preprocess_data',
 '_residues',
 '_set_intercept',
 'coef_',
 'copy_X',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'n_jobs',
 'normalize',
 'predict',
 'rank_',
 'score',
 'set_params',
 'singular_']

In [24]:
print('intercept',model.intercept_) #gives the value of c

intercept 5.633333333333329


In [25]:
print('slope',model.coef_) # value of m

slope [0.54]


In [26]:
y_pred=model.predict(x)

In [27]:
print('predicted response',y_pred, sep='\n')

predicted response
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [28]:
y_pred= model.coef_*x + model.intercept_

In [29]:
mean_squared_error(y,y_pred)

33.75555555555556

In [30]:
print('predicted response',y_pred, sep='\n')

predicted response
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [31]:
x_new=np.arange(5).reshape([-1,1])

In [32]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [33]:
y_new=model.predict(x_new)

In [34]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


In [35]:
r2_score(y,y+)

SyntaxError: invalid syntax (<ipython-input-35-883ce8872722>, line 1)